# Generated by Django 5.0.2 on 2024-02-24 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('dni', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=35)),
                ('apellidos', models.CharField(max_length=35)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otros')], default='F', max_length=1)),
                ('telefono', models.IntegerField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('parentesco', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='acudiente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Academico.acudiente'),
        ),
    ]
