# Generated by Django 5.0.2 on 2024-02-24 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_acudiente_estudiante_acudiente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acudiente',
            old_name='apellidos',
            new_name='apellidos_acudiente',
        ),
        migrations.RenameField(
            model_name='acudiente',
            old_name='dni',
            new_name='dni_acudiente',
        ),
        migrations.RenameField(
            model_name='acudiente',
            old_name='email',
            new_name='email_acudiente',
        ),
        migrations.RenameField(
            model_name='acudiente',
            old_name='fecha_nacimiento',
            new_name='fecha_nacimiento_acudiente',
        ),
        migrations.RenameField(
            model_name='acudiente',
            old_name='nombres',
            new_name='nombres_acudiente',
        ),
        migrations.RenameField(
            model_name='acudiente',
            old_name='sexo',
            new_name='sexo_acudiente',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='codigo',
            new_name='codigo_curso',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='descripcion',
            new_name='descripcion_curso',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='nombre',
            new_name='nombre_curso',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='url_imagen',
            new_name='url_imagen_curso',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='apellidos',
            new_name='apellidos_estudiante',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='dni',
            new_name='dni_estudiante',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='email',
            new_name='email_estudiante',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='fecha_nacimiento',
            new_name='fecha_nacimiento_estudiante',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='nombres',
            new_name='nombres_estudiante',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='sexo',
            new_name='sexo_estudiante',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='apellidos',
            new_name='apellidos_tutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='dni',
            new_name='dni_tutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='email',
            new_name='email_tutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='fecha_nacimiento',
            new_name='fecha_nacimiento_tutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='nombres',
            new_name='nombres_tutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='sexo',
            new_name='sexo_tutor',
        ),
        migrations.RemoveField(
            model_name='acudiente',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='telefono',
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('codigo_tema', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tema', models.CharField(max_length=35)),
                ('descripcion_tema', models.CharField(max_length=300)),
                ('url_imagen_tema', models.CharField(max_length=150)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('codigo_material', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_material', models.CharField(max_length=35)),
                ('descripcion_material', models.CharField(max_length=300)),
                ('url_material', models.CharField(max_length=150)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.tema')),
            ],
        ),
    ]
