# Generated by Django 5.0.2 on 2024-02-24 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0003_rename_apellidos_acudiente_apellidos_acudiente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion_curso',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='descripcion_material',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tema',
            name='descripcion_tema',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_publicacion', models.CharField(max_length=100)),
                ('contenido_publicacion', models.TextField()),
                ('fecha_publicacion', models.DateField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_comentario', models.DateField()),
                ('contenido_comentario', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.estudiante')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.publicacion')),
            ],
        ),
    ]
