# Generated by Django 5.0.2 on 2024-02-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0004_alter_curso_descripcion_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acudiente',
            name='telefono_acudiente',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telefono_estudiante',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='telefono_tutor',
            field=models.IntegerField(null=True),
        ),
    ]
