# Generated by Django 5.0.2 on 2024-03-19 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0005_acudiente_telefono_acudiente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='anoLectivo',
            fields=[
                ('codigo_ano', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Tema',
            new_name='Desempeno',
        ),
        migrations.RenameField(
            model_name='desempeno',
            old_name='codigo_tema',
            new_name='codigo_desempeno',
        ),
        migrations.RenameField(
            model_name='desempeno',
            old_name='descripcion_tema',
            new_name='descripcion_desempeno',
        ),
        migrations.RenameField(
            model_name='desempeno',
            old_name='nombre_tema',
            new_name='nombre_desempeno',
        ),
        migrations.RenameField(
            model_name='desempeno',
            old_name='url_imagen_tema',
            new_name='url_imagen_desempeno',
        ),
        migrations.RemoveField(
            model_name='material',
            name='tema',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apellidos_madre',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apellidos_padre',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='direccion_madre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='direccion_padre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='email_madre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='email_padre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_nacimiento_madre',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_nacimiento_padre',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombres_madre',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombres_padre',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ocupacion_madre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ocupacion_padre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='sexo_madre',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otros')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='sexo_padre',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otros')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telefono_madre',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telefono_padre',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='desempeno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Academico.desempeno'),
        ),
        migrations.CreateModel(
            name='Grados',
            fields=[
                ('codigo_grado', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nivel_educativo', models.CharField(choices=[('A', 'Preescolar'), ('B', 'Primaria'), ('C', 'Secundaria'), ('D', 'Bachillerato')], default='A', max_length=1)),
                ('anolectivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Academico.anolectivo')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academico.grados'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Academico.grados'),
        ),
    ]
