# Generated by Django 5.0.2 on 2024-04-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0008_rename_id_matricula_id_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usu', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=25)),
                ('rol', models.CharField(default='Administrador', editable=False, max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='contrasena',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombre_usu',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='rol',
            field=models.CharField(default='Estudiante', editable=False, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='contrasena',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='nombre_usu',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='rol',
            field=models.CharField(default='Tutor', editable=False, max_length=25, null=True),
        ),
    ]
