# Generated by Django 5.0.2 on 2024-04-27 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0009_admin_estudiante_contrasena_estudiante_nombre_usu_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
