# Generated by Django 5.0.2 on 2024-04-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0010_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('dni_admin', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombres_admin', models.CharField(max_length=35)),
                ('apellidos_admin', models.CharField(max_length=35)),
                ('nombre_usu', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=25)),
                ('rol', models.CharField(default='Administrador', editable=False, max_length=25)),
            ],
        ),
    ]
