# Generated by Django 5.0.2 on 2024-05-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0011_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='url_imagen_curso',
        ),
        migrations.AddField(
            model_name='curso',
            name='imagen_curso',
            field=models.FileField(null=True, upload_to='curso_imagen/', verbose_name='Imagen del curso'),
        ),
    ]
