# Generated by Django 5.0.2 on 2024-05-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0013_estudiante_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='imagen',
            field=models.FileField(null=True, upload_to='imagen_tutor/', verbose_name='Foto de perfil del estudiante'),
        ),
    ]
