# Generated by Django 5.0.2 on 2024-05-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0014_tutor_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desempeno',
            name='url_imagen_desempeno',
        ),
        migrations.AddField(
            model_name='desempeno',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='desempeno',
            name='imagen_desempeno',
            field=models.FileField(null=True, upload_to='desempeno_imagen/', verbose_name='Imagen del curso'),
        ),
        migrations.AddField(
            model_name='material',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='imagen',
            field=models.FileField(null=True, upload_to='imagen_tutor/', verbose_name='Foto de perfil del tutor'),
        ),
    ]
